### ISSUE TITLE
Text styling in full width text

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1304]
Doesn't look to spec. An example can be seen at /consumer-help/managing-credit/

**Comment by kave** [comment]
@jimmynotjim @KimberlyMunoz

**Comment by jimmynotjim** [comment]
I think this is another wagtail output issue

![screen shot 2016-01-05 at 5 21 44 pm](https://cloud.githubusercontent.com/assets/1280430/12129321/d6413d26-b3d0-11e5-96ac-7d47358bd5fc.png)

Not sure what's causing it this time though, doesn't really make sense that it'd be closing empty `p` around the `ul`

**Comment by jimmynotjim** [comment]
@kave I'm stumped on this one, this is the markup

```
<div class="m-full-width-text">
    {{ block.value.source | safe }}
</div>
```

@tnferrell Could it be that the empty paragraphs are in the editor field this time? I don't have access to the admin, but maybe you could screen shot what you're seeing and send it to me?

**Comment by kave** [comment]
@jimmynotjim hmm... i'll have to take a look at this when i get back into the office, don't have access to vpn right now

**Comment by kave** [comment]
@jimmynotjim @tnferrell is this maybe some confusion between wagtail styles & cfpb styles? because the markup looks accurate

Admin side:
<img width="964" alt="screen shot 2016-01-06 at 9 52 14 am" src="https://cloud.githubusercontent.com/assets/254877/12145253/36414c2c-b45b-11e5-9e24-acf95fdb5481.png">

Live:
<img width="975" alt="screen shot 2016-01-06 at 9 52 22 am" src="https://cloud.githubusercontent.com/assets/254877/12145263/3ebc2ba6-b45b-11e5-8c2c-4419d0b54c30.png">

Markup:
![screen shot 2016-01-06 at 9 47 55 am](https://cloud.githubusercontent.com/assets/254877/12145270/4636f078-b45b-11e5-87cd-6aea97e46352.png)

**Comment by jimmynotjim** [comment]
There are style issues, but look at the markup, there's an empty `p` before the `ul`

**Comment by jimmynotjim** [comment]
These are fixed in code and will be updated after the next refresh push
