### ISSUE TITLE
fcm image proportion doesn't look like mockup

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1327]
not sure if this is an issue because i didn't see a preview of the featured content module on a page with a right sidebar, but the image in the fcm looks more square than it should. could it be because we have a lot of text in it? i uploaded a 16:9 image and my screen resolution is 1366x768.

**Comment by sebworks** [comment]
@tnferrell, can you attach screenshots?

**Comment by tnferrell** [comment]
Sorry, here's the URL.. /consumer-help/financial-resources-servicemembers/

![fcm](https://cloud.githubusercontent.com/assets/13967788/12244798/fa6fff2c-b86a-11e5-9fa0-2746b9ef425e.png)

**Comment by jimmynotjim** [comment]
That is indeed because of the amount of text. The image will resize to the height of the FCM, so the content will always dictate the image dimensions

**Comment by schaferjh** [comment]
Does the FCM have a max height per the design manual? If yes, we should probably figure out roughly what the means for a character count.

**Comment by jimmynotjim** [comment]
Hmm, the docs say max 360px, but I think I remember Jen and I discussing that there shouldn't really be a max height. @huetingj can you confirm?

**Comment by huetingj** [comment]
Hello! The intended height for this is 320px (at the largest screen size). There isn't actually a max height because of the way it moves across different screen sizes. I wrote the DM guidelines incorrectly to say 360px, and I'll amend this. Sorry for the confusion!

Looking at the example above, I agree that this is more copy than we envisioned the module to have and that we need to establish a character count. After playing around with content in Illustrator, here are the counts I'm finding that will get the module height in the right range:

Headline: Max 35 char (two lines)
Body copy: Max 160 char (note that you have a little wiggle room if your headline only takes up one line)
CTA link: Max 30 char

Hope this helps. Let me know how it goes, and I'll amend the DM page.

**Comment by huetingj** [comment]
Oh one other thing: Do you see "testimony" as being a reoccurring category? If so, I can add it to our list of tags on the DM page, which is currently this:

![screen shot 2016-01-13 at 11 35 52 am](https://cloud.githubusercontent.com/assets/10562530/12300719/c5c20af0-b9ea-11e5-9e87-7e0c4ef80d9b.png)

Also, has there been discussion about making the tag lowercase and not using the word "Featured?"

**Comment by tnferrell** [comment]
Opened an issue about the casing before I saw this...

#1337

**Comment by tnferrell** [comment]
@huetingj those character counts do help. i updated the copy and our wiki page for that module with those limits to help guide us in the future. 

the categories in the fcm are from a select list in the cms so yes we would be using them repeatedly. but i'm not sure how the current category list was developed. i'd hold off on adding it to the DM until we're sure our list is right. i'll follow up once we've ironed it out.

**Comment by tnferrell** [comment]
Updated issue #1337 to update our categories to be in line with design manual and spec. Closing issue  since all questions have been resolved.

**Comment by huetingj** [comment]
:+1: Thanks @tnferrell!
