### ISSUE TITLE
formatting in text introduction

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1336]
i'm not sure if this is a duplicative issue, i couldn't find it when i was searching the repo, but the text introduction formatting looks off. example can be seen here: /consumer-help/sending-money-abroad/

**Comment by jimmynotjim** [comment]
@tnferrell looking at the inspector, it seems like either the cms is adding `p` tags or they've been added in the input field in the admin. Because of the classname requirement for the lead paragraph, we have to add the `p` in the template here. Could you take a look at the admin and make sure there aren't any there?

**Comment by tnferrell** [comment]
Unfortunately, there isn't an HTML editor in wagtail, so I can't verify if I've accidentally added code. But, I copied the text from notepad, pasted it in, and the P is selected, which I'm assuming means it's in a paragraph tag. I can't unselect the P. Any time you paste text into the rich text box it's selected by default. Hope this helps.

**Comment by duelj** [comment]
Just wanted to note that this issue relates to issue #1366. Many of the other scenarios of where this type of thing is happening are documented there.

**Comment by KimberlyMunoz** [comment]
This field has to be a rich text field because we might have links or bullet points in the lead paragraph so it's an all or nothing thing for potentially stripping extra `p`s. I went in and I couldn't really remove them when once they're in. @jimmynotjim, why couldn't we wrap this in a `div` instead of a `p`?

**Comment by jimmynotjim** [comment]
We've done that before, but I'm concerned how that affects spacing https://github.com/cfpb/capital-framework/blob/canary/src/cf-core/src/cf-base.less#L333-L344

**Comment by tnferrell** [comment]
Just wanted to add to this that we're seeing the font is fine now. But I think it's supposed to be a larger size? /policy-compliance/enforcement/warning-letters/

**Comment by jimmynotjim** [comment]
Yeah, the main issue is still open, it just turned into Avenir when I fixed the base-font. I say we go w/ a div wrapper. @KimberlyMunoz if you haven't, I can do this today.

**Comment by KimberlyMunoz** [comment]
Hey @jimmynotjim, let me know if this issue is open?

**Comment by jimmynotjim** [comment]
Discussed in scrum, lets go w/ the div wrapper because if a `return` gets pasted in or entered, it messes everything up.
