### ISSUE TITLE
Remove Legacy ImageBasic streamfield block

### ISSUE THREAD

**Issue by kurtrwall** [cfpb/cfgov-refresh#1340]
https://github.com/cfpb/cfgov-refresh/pull/1322#issuecomment-170578001

Needs to convert the existing data from the block into the existing image's `alt` field for the new custom Image model.

**Comment by richaagarwal** [comment]
Aren't we still using this?

**Comment by kurtw** [comment]
Yeah but we shouldn't be. The image model that we use has the `alt` attribute that ImageBasic was adding in.

**Comment by anselmbradford** [comment]
@cfpb/cfgov-backends Is this still an issue?

**Comment by chosak** [comment]
Our image model ([`CFGOVImage`](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/v1/models/images.py#L13)) does have an `alt` field that lets you define general alt text for an image when it gets added to Wagtail:

![image](https://user-images.githubusercontent.com/654645/38994543-b241f55c-43b4-11e8-9dc3-645bc314213a.png)

But then the [`ImageBasic`](https://github.com/cfpb/cfgov-refresh/blob/ca9053d66e65ab0f66490fab6f08a4b7354354f8/cfgov/v1/atomic_elements/atoms.py#L115) block lets you further customize that, by adding a different alt tag in each place that the image is displayed:

![image](https://user-images.githubusercontent.com/654645/38994652-f6015954-43b4-11e8-91b9-24dc95b1c97b.png)

Then on top of both of those we also have a custom [`image_alt_value`](https://github.com/cfpb/cfgov-refresh/blob/fb613547d8dbde2488cb65fe465d7102c5496c02/cfgov/v1/jinja2tags.py#L13) Jinja tag that picks which alt text to use. It seems to me like ideally this could be baked into the `ImageBasic` block rendering; if I recall correctly from pairing with @Scotchester on #2920 that was difficult because we don't consistently use `{% include_block %}` throughout.

Bringing this back to the issue at hand, my read is that as long as we want to be able to override an image's alt text per block, then we need to keep `ImageBasic` around, and this can be closed. @Scotchester does that all seem right to you?

**Comment by Scotchester** [comment]
Thanks for digging back into all that, @chosak. That does all seem right to me.
