### ISSUE TITLE
Sidebar elements need spacing sub-landing pages

### ISSUE THREAD

**Issue by duelj** [cfpb/cfgov-refresh#1388]
Molecules in the sidebar on sub-landing pages are missing the 60px of space between them. There are also spacing issues of the links within these elements. Looks like all links are not given a hard break between them but run together like a paragraph. They should follow the updated spacing 

<img width="436" alt="screen shot 2016-01-28 at 10 51 14 am" src="https://cloud.githubusercontent.com/assets/6873734/12649559/18d6c94c-c5ad-11e5-9aff-410915eb0788.png">

[Information for Servicemembers](http://content.refresh.demo.cfpb.gov/consumer-help/financial-resources-servicemembers)

**Comment by schaferjh** [comment]
Looking at the sidebar options in Wagtail, it appears that instead of having options for molecules/organisms, content is presented with a bunch of atoms, which is impacting the spacing issues, among other things. 

Let's have a BEWD/Content chat next week about replacing the atoms with molecules/organisms. I will look for time and likely connect this to the convo for #1258.

**Comment by sebworks** [comment]
I think they should be using the `Related-Links` molecule. I think the issue was raised in https://github.com/cfpb/cfgov-refresh/issues/1328 as well.

**Comment by kave** [comment]
@schaferjh @duelj @sebworks was a resolution found for this?

**Comment by duelj** [comment]
@kave - Not that I am aware of. From the design end we know the space that should exist but I don't think it has been resolved from the FEWD end yet. There was some discussion between, @ajbush and @KimberlyMunoz around spacing for browse pages where sidebars become pre-footers. Sounds like this is related but, I don't thing there was resolution yet there either.

**Comment by KimberlyMunoz** [comment]
Nope, the issue we've been discussing with prefooters a different one. From the front-end perspective, we have the specs in for all the sidebars, but we can't fix the spacing in the cases where content is using atoms instead of molecules/organisms and we talked with Jess about switching those over.
.
This issue is one between content/BEWDs about replacing the atoms with molecules/organisms. @schaferjh, what's the status on that?

**Comment by schaferjh** [comment]
Thank you for the nudge @KimberlyMunoz. 

I talked about this with @kurtw, @sarahsimpson09, @tnferrell and @Schlachtmeyer last week. IIRC, we decided that content will move everything out of the atoms before the BEWDs delete the atoms. Content folks -- has that happened/is that happening? Or, do you guys have a different memory of that conversation?

**Comment by schaferjh** [comment]
Follow up -- content has moved all important data out of the atoms, and we are now ready for @kurtw or @kave to remove the atoms from the sidefoot. Once that has been done, this issue should be resolved.

**Comment by KimberlyMunoz** [comment]
This was fixed a while ago. Any new spacing issues should be re-reported.
