### ISSUE TITLE
Doc detail template: Author field needs to be conditional

### ISSUE THREAD

**Issue by sarahsimpson09** [cfpb/cfgov-refresh#1391]
Currently, even when field needs to be blank, the word "By" still shows up on the page preview
![doc detail author issue](https://cloud.githubusercontent.com/assets/9706023/12684442/f0a8cfa2-c68c-11e5-87c7-d89c3118997a.png)

**Comment by KimberlyMunoz** [comment]
Part of this requires work from content. In the CMS, you'll have to click the trashcan so that there's no authors being added, right now a blank author is being added. The dash is a front-end problem and I'll still fix it.

![image](https://cloud.githubusercontent.com/assets/1860176/12728058/fee9d8be-c8ed-11e5-9ee5-167da90cfade.png)

**Comment by sarahsimpson09** [comment]
Thanks! I'll go through and make those updates to the doc detail pages.

**Comment by KimberlyMunoz** [comment]
Pushed up a fix to take care of a rogue dash that still appears!
