### ISSUE TITLE
can the filter on browse filterables actually filter by title?

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1456]
Can a person search using the title field in the filter organism to find documents? If not, we may want to consider not having it as an option. Tagging @schaferjh so she can keep up with the convo.

**Comment by schaferjh** [comment]
Just to clarify, this is a question that came up in review of one of the browse filterable pages that content recently created -- the filter had an option to include "title" as a field in the filter. I was surprised by this because I didn't think we had set up the filters to search the title field of the associated documents. 

A. Do the filters currently support filtering based on title? (I think this is a @kurtw or @kave question)
B. If no, at some point after our initial launch, it would be interesting to explore that functionality.

**Comment by kurtw** [comment]
Yes, the filter currently supports title search.

**Comment by schaferjh** [comment]
@kurtw that's awesome news! 

To be clear, is it true that:
- The title field is a plain text entry field
- a user can type any word or combination of words into the "title" field, and when they click "Apply filter" the filter will only return Post preview items whose title includes that word or combination of words

And is the field set up to handle usage of quotation marks, commas as the user might expect from other search experiences? (If no, that is okay, just trying to ascertain the functionality)

**Comment by kurtw** [comment]
The user can search for the title of any page in the list with a case insensitive manner, but it doesn't support things like quotation marks. It's a character for character search, not very complex. If there's a quotation mark in the title, then it can find it as long as the user put it in the right order of the searched text. 

For example, user searches `"term"` then the page with the title `The second "term" of the office` will be returned but not `The second term of the office`.

**Comment by schaferjh** [comment]
Ok, this is very helpful. @tnferrell @sarahsimpson09 @Schlachtmeyer Let's discuss which filters should use the title field and which shouldn't. I'll put it on the agenda for one of our Team Working Sessions next week (week of 2/22/16).

**Comment by kurtw** [comment]
Closing since the question was answered. Thanks everyone!
