### ISSUE TITLE
Font size changes in Item Introduction / doc detail page

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1466]
For the Reports pages I'm using the doc detail template with the Item Introduction for each report. The font size of the paragraph text seems to depend on whether or not there's a hard return? It starts out as a large font size and then I can force it to a smaller font size by inserting a hard return - and then if I delete the hard return it stays at the smaller size. To me the smaller size looks better, but there should be a better way to make that happen?

Large font size:
![image](https://cloud.githubusercontent.com/assets/14129916/13113041/67b2f5e6-d55b-11e5-92ea-f4327470983c.png)

Small font size:
![image](https://cloud.githubusercontent.com/assets/14129916/13113051/711c2576-d55b-11e5-808d-b8576486c2e9.png)

**Comment by KimberlyMunoz** [comment]
The spec calls for the larger font size, right? @ajbush and @duelj?

This might be the same issue as #1336.

**Comment by duelj** [comment]
@KimberlyMunoz - yes the [spec](https://github.cfpb.gov/flapjack/Modules-V1/wiki/Text-Introduction) calls for the larger (H3) subheading to to the page title. It looks like it is basically the same as the #1336 issue. One of the other things build does not often make use of was the rule line at the bottom of the text/page introduction to define that section from the rest of the page content. I don't know if this is just not getting add in Wagtail, or if it is not part of the organism. I think we will want to make sure it is an option in the CMS, so that we can use it in the future.

**Comment by Schlachtmeyer** [comment]
@duelj For each report I have the choice of a Text Intro or an Item Intro. The Text Intro has no date so I've been using the Item Intro. The Text Intro has the option of a line below, but the Item Intro doesn't. (And I can't get Wagtail to save a page with a Text Intro, so I can't show you!)

**Comment by KimberlyMunoz** [comment]
We discussed in Team Working session and the decision was to put any content that needs to be smaller like that in the Full-Width molecule. We're going to make sure that returns don't break the h3 intended size for that introduction paragraph in #1471.

**Comment by KimberlyMunoz** [comment]
Fix has been pushed up to refresh!
