### ISSUE TITLE
Need tighter spacing at the start of a new section

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cfgov-refresh#185]
From @ell0ell0:

> need tighter spacing here at the start of a new section

> ![screen shot 2014-10-29 at 1 51 33 pm](https://cloud.githubusercontent.com/assets/3589375/4831433/7899cdf0-5f94-11e4-8fcc-3ef696fa2217.png)

**Comment by jimmynotjim** [comment]
Is this still an issue? cc @ajbush @duelj

**Comment by duelj** [comment]
Kinda. Now it just seems like its a different issue. This issue can probably get closed, I think we will want to update pages so that the pages match the spacing that @ajbush has in his [mockups](https://github.cfpb.gov/flapjack/global/issues/21#issuecomment-43856) for the navigation adjustments (with titles, breadcrumbs, and all).

**Comment by KimberlyMunoz** [comment]
Hey @duelj,

Open up a new issue here or in JIRA on the spacing you would like site-wide and we'll take a look at it.
