### ISSUE TITLE
Proposal: Initial Release Cadence

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/cfgov-refresh#2172]
At the end of a sprint, we:
- Create a new _branch_ from the current 'master' (what we now call flapjack)
- Create a release from that branch, and deploy it to beta (or, a new 'staging' server created for this purpose)
- let the release "burn in" on beta/staging for a few days (remainder of that week?). If any fixes are neccessary before going to production, they are commited to the release branch, and back-merged to master. A new "hotfix" releases are created from the branch as needed to get urgent changes onto beta 
- Deploy the release to www and content.
- If any urgent changes are needed before the _next_ release goes to www, they are treated as hotfixes to the version currently on www. 

As we gain more confidence in automated testing and other feedback loops, the cycle could shrink to by-week instead of by-sprint, perhaps even shorter.
## Sample sprint schedule (two weeks, sprints starting on Wednesday)

M:
T:  Sprint "foo" ends (release branch "foo" created, deployed to beta)
W: Sprint "bar" begins
T: 
F:

M:  Release branch "foo" deployed to www and content
T:
W:
T:
F:

M:
T: Sprint "bar" ends (release branch "bar" created, deployed to beta)
W: Another sprint begins
T:
F:

**Comment by kave** [comment]
yea i like this approach. the only issue i can foresee is that `beta` for the large part goes barely touched these days by content & general users unless there's user testing going on. 
Maybe instead of pushing to `beta`, maybe we push to `content` and let it burn instead. Since its being actively used and bugs due to new code has a higher likely-hood to be found if they even exist.

**Comment by rosskarchner** [comment]
My fear about using content for this, is that in the past we've had problems when the schemas on content and production don't match--  (say, jobs or AskCFPB are being synced, but the content table structure doesn't match production. Things blow up)

This is why the server is currently called 'content', because using it both for editorial work and code staging was creating problems.

**Comment by kurtw** [comment]
In the meantime, I don't see why we couldn't just keep build and beta for these in-dev code features.

**Comment by rosskarchner** [comment]
@kave's main point is worth thinking about though: content is the one way to get pending changes onto a site people actually use on a daily basis.

**Comment by willbarton** [comment]
Perspective of someone who hasn't had to deal with any of this yet: 

@rosskarchner can you say more about the schema problem? It seems like code and schema should be in sync with each other, at the very least, and if it isn't, we should know (i.e., blow things up)? This sounds like a problem we should solve.

Otherwise, it seems like the single best way to get feedback is put the code where the people are — I would agree conceptually with @kave.

**Comment by rosskarchner** [comment]
@willbarton currently, some data is migrated from content to www via an SQL dump and load. AskCFPB and careers are probably the biggest examples. 

Recently, the team working on AskCFPB made a lot of changes, including schema changes, and it was previewed on content before going to production. This left us in a state where, if someone had clicked the button to migrate content, 💣 💥 -- we would have moved the new schema to www without the new code.

This wasn't a huge deal, though-- we just had to schedule a freeze. 

I think maybe @kurtw @richaagarwal or @kave might be able to advise, but the single-database tables (like our Wagtail types) might even be more fragile. What exactly happens when there's a field that content knows about but production doesn't?

**Comment by willbarton** [comment]
@rosskarchner Ah, I understand. So the expectation underlying the use of content is that it is in sync with production?

**Comment by rosskarchner** [comment]
right, at the very least in terms of database schemas

**Comment by kurtw** [comment]
@rosskarchner since the migration script runs when the content deployment runs and content and production share a database then anything that utilizes that new field will throw errors.

Even worse, if we make major schema changes then potentially this could break huge portions of the site.  Akamai always gives us this buffer, but we need to seriously rethink how we're deploying to both of these environments if this is all true. Maybe we just configure the job to deploy to both locations simultaneously and that we set up beta to mirror content for testing beforehand.

**Comment by rosskarchner** [comment]
Mostly good, except that beta-mirroring content, means things we don't mean to publish yet get published...

What if every deploy to beta included:
- mirroring the prod database
- exercising all the migrations between the prod and beta codebase

That way, we can always be confident that our migrations are running.

**Comment by marcesher** [comment]
@kurtw @rosskarchner @kave Crazy idea, probably heresy in Django land: stop using migrations for schema changes.

Hear me out: in lots of other tech, it's not a "thing", or at least not a given, that code and database are so tightly coupled. In fact, it's often considered A Good Thing(tm) to decouple database migrations and code, such that code can work with a version of the database 1 version forward and back. In practice, this generally means 2-stage schema changes: a schema change prior to code deploy (like expanding a column, adding a new one, etc) that the *existing* software can run on without error. Then, the code is deployed, and it continues to run fine... now the code and schema are completely in sync. 

Granted, it's harder to manage. But as you know, the current situation is hard to manage as well.

So, all I ask is that you don't immediately either a) toss out the idea of decoupling them, or b) think that we *must* use migrations for managing schema changes. DB and code can remain less coupled, even in django-land.

**Comment by rosskarchner** [comment]
💭 💣

**Comment by rosskarchner** [comment]
This discussion has moved elsewhere
