### ISSUE TITLE
Does semver make sense in this repo?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#312]
Semantic versioning makes sense if this repo was for a library that's imported into another project (like CF), but I'm unclear on the benefit of following semver in this particular repo? It doesn't appear [to be maintained](https://github.com/cfpb/cfgov-refresh/blob/gh-pages/CHANGELOG.md) in this way. Can we remove https://github.com/cfpb/cfgov-refresh#how-this-repo-is-versioned and https://github.com/cfpb/cfgov-refresh/blob/gh-pages/CHANGELOG.md ?

**Comment by jimmynotjim** [comment]
I'd be hesitant to drop semver or the changelog. While the project shouldn't ever become a dependency, semver creates a nice rule to follow for releases. The changelog is important for pinpointing when a bug or issue a developer is seeing locally might have been created (since this is open source) and informing the general public what progress we're making as the project develops (just like apps in the App Store). This is why the additions, removals, and changes headings in PRs are great, they basically write your changelog for you.

Lastly "Don’t let your friends dump git logs into CHANGELOGs™" - [Keep a Changelog](http://keepachangelog.com/)

**Comment by anselmbradford** [comment]
When would we be updating the changelog? At the end of a sprint? 

(also, fixing my typo... :))

**Comment by Scotchester** [comment]
We've been terrible at keeping it up, but I think it will become important when we start doing regular deployments to the public beta site. At that point, I think we'll want to be much better at saying what's in each release.

**Comment by jimmynotjim** [comment]
@anselmbradford that depends. Typically, changelogs are only updated when the deployment branch is updated (though right now our deployment branch is actually all envs). The nice thing about using semver tags is that we can always always tag a release, but mark it as unstable on Github and when it goes into production just switch it over. This means your really tagging along the way and release tags take no time.

**Comment by anselmbradford** [comment]
Tagging is discussed in [GHE]/flapjack/Getting-started-with-Flapjack/blob/master/front-end/workflow-guide.md#tagged-releases
