### ISSUE TITLE
Deprecated hud-api-replace 404 error

### ISSUE THREAD

**Issue by kzisme** [cfpb/cfgov-refresh#4104]
Short description explaining the high-level reason for the new issue.

## Current behavior
Currently receiving a 404 error when attempting to send a request to 

> http://www.consumerfinance.gov/hud-api-replace/zip_code_here

## Expected behavior
Previously this endpoint returned json data - it seems the endpoint has moved.

I do see that there was a commit - https://github.com/cfpb/cfgov-refresh/pull/4086 to deprecate this, but has the new functionality been ported over to the redesign/refresh?

**Comment by sdicken** [comment]
My company also has run into this issue and affected our production systems yesterday. So far, the only replacements we have found are

http://files.consumerfinance.gov/a/assets/hud/jsons/{zipcode}.json (like before - not a public API)
https://data.hud.gov/housing_counseling.html (public API, but no zipcode input option)

We could use advice on which to prefer of the above two options.

**Comment by Shane0mac92** [comment]
Agreed. We need the government more than ever right now. Please help!

**Comment by schlechtyj** [comment]
Yep. Help.

**Comment by kzisme** [comment]
@sdicken - Where/how did you go about requesting access to the first option you provided?  One of the contributors might still give us some advice too.

**Comment by sdicken** [comment]
@kzisme I did not encounter any access control on that link to files.consumerfinance.gov. Replace the {zipecode} with the numeric zip code you desire and a JSON file should download in your browser. I found that link as I was desperately trawling this repo for a quick fix solution yesterday.

**Comment by kzisme** [comment]
@sdicken Thanks!  That seems to be a nice band-aid fix.  Hopefully that isn't deprecated in the coming weeks/months as well.  Based on the other [repos readme](https://github.com/cfpb/django-hud/blob/master/README.md) it _does_ seem like they are going to be replacing that functionality with something, but the only thing I came across yesterday was a tool that only supported zip code searching (without API functionality). 

I suppose I'll ping @rosskarchner and @richaagarwal to see if they might be able to provide any additional information.

**Comment by ascott1** [comment]
@kzisme @sdicken @Shane0mac92 Thank you for reaching out. The prior Find a Housing Counselor API was an undocumented public API that is no longer in use by the Bureau. Our site is in the process of undergoing a technology upgrade and as part of the transition, we have removed this legacy API. Due to the legacy nature of the code, we could not reliably update it and ensure data integrity.

The officially supported Bureau resource for this information can be found at https://www.consumerfinance.gov/find-a-housing-counselor/ . If you are in need of an API solution, HUD offers an officially supported [public API](https://data.hud.gov/housing_counseling.html) for locating housing counselors. We also offer the code of the [legacy API](https://github.com/cfpb/django-hud) , if you would like to host a version of the prior API yourselves. The recent code that powers the current implementation of the page can be found within this project. 

I hope this is helpful and I do apologize for any inconvenience this has caused.

**Comment by sdicken** [comment]
Thanks!

**Comment by ascott1** [comment]
Based on the feedback we received, we've _temporarily_ re-enabled this API to allow users time to transition to something new. We intend to permanently decommission it at the end of next week. We recommend using the official [public HUD API](https://data.hud.gov/housing_counseling.html) as a permanent solution for locating housing counselors, which is what we use. If you need some of the features that we have developed on top of the HUD API, feel free to explore the code of [our legacy API](https://github.com/cfpb/django-hud) or the code that powers the current implementation of the page, which can be found within this project. 

I want to also note that there is no guarantee of long-term support of json files that @sdicken noted above.

**Comment by Shane0mac92** [comment]
@ascott1  Thank you so much sir! We appreciate your support and help and will update our API in the coming days to use the appropriate calls.

You are what is formerly known as 'The Man'
