### ISSUE TITLE
Keeping side nav language consistent with paths

### ISSUE THREAD

**Issue by jameshupp** [cfpb/cfgov-refresh#469]
Something that has come up as we've made edits over the last few weeks is that in some cases stakeholders requested a change to a page title within their section. I know where to make this change, but I want to keep URL and page title consistent. I'm not going to change paths, though, since I'm sure there are references to these paths in places I'm not familiar with. I'm seeking clarity on the right way to handle this.

For instance, in the file below, the page currently labeled "Future Requests" under Doing Business with Us should be "Upcoming Procurement Needs".

https://github.com/cfpb/cfgov-refresh/blob/flapjack/doing-business-with-us/_vars-doing-business-with-us.html

Should I make the text change and then alert devs? Should I just file an issue on it? @anselmbradford @jimmynotjim @sebworks what do you all prefer?

**Comment by anselmbradford** [comment]
Unless it's something tiny, I'm a fan of opening an issue, then if you open a PR, add "Fixes #<issue number>" (see [this on autoclosing issues](https://help.github.com/articles/closing-issues-via-commit-messages/)) in the commit message.

You might also find Jimmy's PR template helpful https://gist.githubusercontent.com/jimmynotjim/e2e182eea6dedeb57109/raw/b0f2073f6eb2f2379edfa2fb39edef8bf1b08e47/gistfile1.txt, which you can copy and paste in the PR message.

I'm not sure about how to handle the paths, like if we want to have path aliases at this stage in the game, since the site is still under development.

**Comment by jameshupp** [comment]
But what is tiny? Like, I can change the content, and honestly I could change 'future-requests' to 'upcoming-procurement-needs'. But then I need to find other references to 'future-requests' and change them. None of which is a lot of work, but it introduces another set of less skilled hands that can screw up references to future-requests. Although I guess I should factor "be careful not to break things" into estimation of amount of work. So maybe I'm answering my own question. Okay, I'll file issues on these sorts of things.

**Comment by anselmbradford** [comment]
> But what is tiny? Like, I can change the content, and honestly I could change 'future-requests' to 'upcoming-procurement-needs'. But then I need to find other references to 'future-requests' and change them. None of which is a lot of work, but it introduces another set of less skilled hands that can screw up references to future-requests. Although I guess I should factor "be careful not to break things" into estimation of amount of work. So maybe I'm answering my own question. Okay, I'll file issues on these sorts of things.

Kinda a rule of thumb is if it's quicker to fix than to file an issue, just go ahead and fix it. Filing an issue is mostly a reminder for yourself and a courtesy to the team to know what's going on. It gets a little weird here because we have Jira tasks too, but [GHE]/flapjack/Getting-started-with-Flapjack/blob/master/02-front-end/workflow-guide.md#when-should-i-open-a-github-issue-when-should-i-open-a-jira-task may help provide guidance with that.

In an ideal world there'd be a nice reference chain from issue > PR. If you don't think you're going to get to something immediately, file an issue for it (this gives everyone a heads up about it, allows someone else to close it if they get to it first, etc.), but a PR still provides a forum where comments can happen, so it's not egregious if a PR doesn't close an associated issue.

**Comment by jimmynotjim** [comment]
I'll leave the large/tiny discussion to you guys, you've got it covered.

For the url slug, I think it's ok to change slugs right now while things are still in development. Once things start to go live (on CF.gov not beta) we will need to add redirects to ensure we don't break existing links and cause 404s. Just make sure to note it in the PR ##Notes section

**Comment by jameshupp** [comment]
Excellent, thanks. @sarahsimpson09 let's make sure we make note of all this for content management process stuff.

**Comment by anselmbradford** [comment]
Can this be closed?

**Comment by anselmbradford** [comment]
Closing this since James is off to greener pastures... re-open if necessary.
