### ISSUE TITLE
Links in contact us expandables are missing bottom padding

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#487]
A contact us expandable that doesn't have a link has proper bottom padding, see:
![screen shot 2015-04-21 at 1 36 46 pm](https://cloud.githubusercontent.com/assets/704760/7258639/e156bc2a-e82b-11e4-9987-1b161930ed2f.png)

However, when a link appears the bottom padding disappears:
![screen shot 2015-04-21 at 1 36 52 pm](https://cloud.githubusercontent.com/assets/704760/7258658/fbe78010-e82b-11e4-8a90-a76c7cb1f3cb.png)

See [GHE]/github-enterprise-assets/0000/0087/0000/4588/58ff79b0-2180-11e4-97f0-aa852c8e9728.png for reference.

**Comment by jimmynotjim** [comment]
Refer to DF-1791 in Jira

**Comment by KimberlyMunoz** [comment]
This looks like an issue in cf-expandables where the `margin-bottom: 0` on  `.expandable-group .expandable_content` overwrites `.expandable__padded .expandable_content` margins when you use them together.

We haven't noticed before because there's usually some spacing in the last paragraph to prevent other expandables from looking smushed, but it's an issue our other expandables too.

**Comment by anselmbradford** [comment]
:-(

**Comment by KimberlyMunoz** [comment]
The larger issue isn't fixed, but wrapping that bottom link in a paragraph has reduced the effect a bit. I say we close this one and keep the cf-expandables issue open.

![image](https://cloud.githubusercontent.com/assets/1860176/7662672/63631fce-fb2d-11e4-8b0b-cf0686734608.png)
