### ISSUE TITLE
Can `section_vars` be removed

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#592]
`section_vars` are defined in one file but I can't find anywhere else where they are used. Are they an artifact that can be removed? https://github.com/cfpb/cfgov-refresh/blob/flapjack/_layouts/layout-side-nav.html#L12

cc @Scotchester @virginiacc

**Comment by Scotchester** [comment]
Hmm... it does appear to be legacy code. You can see on [L22 in that same file](https://github.com/cfpb/cfgov-refresh/blob/flapjack/_layouts/layout-side-nav.html#L22) that it's actually using `vars.nav_items`, instead of what's set in the block you pointed to.

@himedlooff any idea why you might have left this code in when you created `layout-side-nav.html`?

**Comment by himedlooff** [comment]
Yeah, looks like legacy stuff. One interesting thing that it does though is it points you to the docs for setting up nav vars if you forget tot set them: https://github.com/cfpb/cfgov-refresh/issues/592#issuecomment-105911772
