### ISSUE TITLE
Strangely Formatted Featured Topic in /newsroom/

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#628]
Hey @schaferjh,

A few things got connected to make the Featured Topic work. Do you know if this is how it is supposed to look?

![screen shot 2015-06-05 at 5 57 50 pm](https://cloud.githubusercontent.com/assets/1860176/8016033/681d9758-0bac-11e5-843b-b046c1df1bdc.png)

**Comment by schaferjh** [comment]
Yeah, that does not look right. Are all those links on the right marked as being part of the payday debt traps item?
@duelj The designs I could find for this featured topic space on the newsroom repo all seem out of date -- would you give some insight on what's intended here?

**Comment by kurtw** [comment]
The links are in the same WP post as the "Ending payday debt traps" so yes.

**Comment by duelj** [comment]
The featured topic section that is currently on beta was an MVP style for use because I think there was some concern around time to build a "fuller" version and if the department would be able to fill it out. My impression is that our intention would not be to include full URL's on our links which would help with the length. Adidtionally, @jameshupp could speak to this but I believe we landed on "Featured topics" falling under filters as that module would act as a normal post would in the roll. I was on the fence with this handing but thought it was worth mentioning as well. 

##### [Example](https://github.cfpb.gov/flapjack/newsroom/issues/1#issue-10431) of current format design: 

![screen shot 2015-06-08 at 1 58 24 pm](https://cloud.githubusercontent.com/assets/6873734/8041489/86101b14-0de6-11e5-849e-3daf7da88afc.png)


##### ["watchroom" 2.0](https://github.cfpb.gov/flapjack/newsroom/issues/1#issuecomment-26774) (the featured topic section)
The ideas for this was that the featured topic section would be expandable so that we could minimize the amount of space it would take at default and allow for a substantial number of links to still be housed under it. 

|Default|Expanded|
---|---
|![screen shot 2015-06-08 at 2 00 12 pm](https://cloud.githubusercontent.com/assets/6873734/8041526/c6287566-0de6-11e5-8018-bd72a85ad64c.png)|![screen shot 2015-06-08 at 1 53 07 pm](https://cloud.githubusercontent.com/assets/6873734/8041368/c4641d08-0de5-11e5-8672-3d9b33ea600f.png)|

**Comment by schaferjh** [comment]
Ok, so --

**Short term:** For the MVP, the related links should be actual copy not plain URLs.
* Do the links have copy associated with them in WP that is not being pulled through? @kurtw or @sarahsimpson09 

**Medium term:** We need to allocate some time to considering the beyond MVP design and UX of this featured topic section, including the placement of it relative to the filter options.
* Going on the design/UX backlog

**Comment by kurtw** [comment]
The copy associated with the links didn't RAMP over. It's a bug in RAMP. I had @sarahsimpson09 RAMP the featured topics over so that should be fixed after a reindex.

**Comment by KimberlyMunoz** [comment]
The MVP is complete. I'm closing the Github issue.
