### ISSUE TITLE
Create template macro for reservation link

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#834]
Move generation of reservation link to a template macro, since it appears [here](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/events/_single.html#L36-L38) and [here](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/events/_event.html#L79-L83) and would be easy to miss if one or the other had updated language in the email body.

**Comment by jimmynotjim** [comment]
Do we have any plans on implementing a form rather than mailto links? There are a lot of people that don't use the OS mail app and in many cases you can't set another as the default (this happens to me often on my phone), causing the OS app to open, and ask you to set up an account. You then have to copy the link and edit it when you paste it in a third-party app because it includes the title and body content.

**Comment by KimberlyMunoz** [comment]
That sounds like a UX question. @schaferjh?

**Comment by schaferjh** [comment]
We don't have immediate plans for form implementation here but it's a good thing to keep an eye on. I'd like to get a handle on our forms elsewhere before we start expanding instances, but it's a valid point!

**Comment by anselmbradford** [comment]
Closing this as `events/_single.html` and `events/_event.html` are gone. Tagging the bewds if they see redundant generation of an event RSVP link on the backend that could be inconsistent. @kurtw @kave @richaagarwal
