### ISSUE TITLE
Move shared footer object to homepage page object

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#889]
https://github.com/cfpb/cfgov-refresh/blob/flapjack/test/browser_tests/shared_objects/footer.js is technically just hitting the homepage, so could be page_object/homepage.js and have the footer as a property, since the associated tests are just checking the homepage.

**Comment by KimberlyMunoz** [comment]
So I know that it's technically hitting the homepage, but I think the header and footer should be broken out into their own files because they aren't unique to the homepage. If someone wanted to run the tests on a different page they should be able to without getting all the homepage overhead.

Also we used the run the tests by reloading the page on every actions, one or two reloads to keep it a bit more modular shouldn't hurt. :smiley:

**Comment by anselmbradford** [comment]
We could have both :smile:  Have a footer and header test that both hit the homepage:

```
browser_tests/page_objects/page_homepage.js
browser_tests/spec_suites/footer.js
browser_tests/spec_suites/header.js
```

Right now the footer would be the only thing in the homepage object. If it were to grow unmanageably large, we could have:

```
browser_tests/page_objects/page_homepage_header.js
browser_tests/page_objects/page_homepage_body.js
browser_tests/page_objects/page_homepage_footer.js
```

It's just that `shared_objects/footer.js` is identical to a `page_object` but isn't in that directory.

**Comment by sebworks** [comment]
How about the changing the footer code from : 
 ```
this.get = function() {
    browser.get( '/' );
};
```

to :

```
this.get = function( url ) {
    browser.get( url || '/' );
};
```

**Comment by anselmbradford** [comment]
More shared_objects have been added so this issue isn't applicable anymore.
