### ISSUE TITLE
Code for paying for college comparison tool?

### ISSUE THREAD

**Issue by ErieMeyer** [cfpb/cfgov-refresh#897]
Hi hi! Former CFPBer and huge Paying for College fan here. Could you open the repo (or point me to it) for Paying for College? http://www.consumerfinance.gov/paying-for-college/compare-financial-aid-and-college-cost/

cc @saintsoup52 @virtix 

Apologies for opening the issue here -- wasn't sure the best place.

:us:

**Comment by jimmynotjim** [comment]
You're going to want to chat with @mistergone, I know he worked on that project.

**Comment by mistergone** [comment]
Hey @ErieMeyer! I know @rosskarchner and I discussed open-sourcing it earlier this year, and there was some effort involved (I don't know if he ever got to it). I hate to say it, but the front-end code is pretty much as-is, meaning that it's just one big JavaScript file that isn't minified and can easily be taken from the site itself. The rest is a very simple API that just serves the school data.

Hopefully, Ross might have more of an update on open-sourcing it. Otherwise, I'd be very happy to talk to you about PfC (both the code and my general love for the project). :dancer: :octopus:

**Comment by marteki** [comment]
Hey @ErieMeyer! ScrumMaster for Paying for College here. We'll start officially working on it again tomorrow, and design/development's tentative plans are to open it up, all up. I'll have more concrete details after our Gate 0 meeting tomorrow. Sorry for the delay!

**Comment by ErieMeyer** [comment]
Hooray! Thanks everyone! We will grab the JavaScript now and will be enthusiastic customers once it's open.

Thank you!
