### ISSUE TITLE
gulp watch should build project before watching

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#912]
It's possible to run `gulp clean && gulp watch` and break the watch task. It seems like `gulp watch` should first build the project before watching it? cc @jimmynotjim

**Comment by jimmynotjim** [comment]
I haven't ever had a watch task build first. Traditionally I've included the build task in the setup instructions. I do think this makes sense here. Since our build task doesn't include linting/testing and only runs on changed files, it will have minimal affect on the initial time the watch task takes to start up.

**Comment by jimmynotjim** [comment]
Closing because it's not possible to complete the build before browserSync starts watching, causing the browser to open with Jinja errors.

**Comment by anselmbradford** [comment]
Not sure if this fits, but saw this recently http://stackoverflow.com/questions/22824546/how-to-run-gulp-tasks-synchronously-one-after-the-other

**Comment by jimmynotjim** [comment]
That only works for the code executing within the task itself, not the dependent tasks. So you can run clean before styles like

```
gulp.task( 'styles', ['clean'], function() {
  //styles stuff in here
} );
```

but you can't guarantee clean would complete before styles here because they're run async

```
gulp task( 'styles', function() {
  // styles stuff here
} );
gulp task( 'build', ['clean', 'styles'], function() {
  //other build stuff
} );
